/**
 * Pushes recommended tags to Etsy listings.
 * Reads from data/tags-recommended.json (generated by generate-tags.ts).
 *
 * Safety:
 * - Dry-run by default
 * - Shows diff before pushing
 * - Auto-refreshes OAuth token
 *
 * Usage:
 *   npx tsx src/scripts/update-tags.ts              # dry run all
 *   npx tsx src/scripts/update-tags.ts --apply       # push all
 *   npx tsx src/scripts/update-tags.ts --id 1888876448          # dry run one listing
 *   npx tsx src/scripts/update-tags.ts --id 1888876448 --apply  # push one listing
 */
import "dotenv/config";
import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { getAccessToken } from "../etsy/auth.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TAGS_PATH = join(__dirname, "../../data/tags-recommended.json");

const API_KEY = `${process.env.ETSY_API_KEY}:${process.env.ETSY_SHARED_SECRET}`;
const BASE = "https://api.etsy.com/v3/application";

const apply = process.argv.includes("--apply");
const idFlag = process.argv.indexOf("--id");
const targetId = idFlag >= 0 ? parseInt(process.argv[idFlag + 1]) : null;

interface TagRec {
  listing_id: number;
  title: string;
  currentTags: string[];
  recommendedTags: string[];
}

async function updateTags(listing: TagRec, token: string): Promise<boolean> {
  const currentSet = new Set(listing.currentTags.map((t) => t.toLowerCase()));
  const recSet = new Set(listing.recommendedTags);

  const added = listing.recommendedTags.filter((t) => !currentSet.has(t));
  const dropped = listing.currentTags.filter((t) => !recSet.has(t.toLowerCase()));
  const kept = listing.recommendedTags.filter((t) => currentSet.has(t));

  // Skip if no changes
  if (added.length === 0 && dropped.length === 0) {
    console.log(`${listing.title.slice(0, 60)}`);
    console.log("  No changes needed\n");
    return true;
  }

  console.log(`${listing.title.slice(0, 60)} (${listing.listing_id})`);
  console.log(`  ${listing.currentTags.length} → ${listing.recommendedTags.length} tags`);
  if (kept.length > 0) console.log(`  KEEP:  ${kept.join(", ")}`);
  if (added.length > 0) console.log(`  + ADD: ${added.join(", ")}`);
  if (dropped.length > 0) console.log(`  - DROP: ${dropped.join(", ")}`);

  if (!apply) {
    console.log("  [dry run]\n");
    return true;
  }

  // Push to Etsy — PATCH /shops/{shop_id}/listings/{id}
  const SHOP_ID = 56796619;
  const res = await fetch(`${BASE}/shops/${SHOP_ID}/listings/${listing.listing_id}`, {
    method: "PATCH",
    headers: {
      "x-api-key": API_KEY,
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      tags: listing.recommendedTags,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    console.log(`  ERROR: ${res.status} ${body}\n`);
    return false;
  }

  const result = (await res.json()) as any;
  console.log(`  ✅ Updated! Tags: ${result.tags.join(", ")}\n`);
  return true;
}

async function main() {
  const recs: TagRec[] = JSON.parse(await readFile(TAGS_PATH, "utf-8"));
  const token = await getAccessToken();

  const targets = targetId
    ? recs.filter((r) => r.listing_id === targetId)
    : recs.filter((r) => r.recommendedTags.length > 0);

  if (targets.length === 0) {
    console.log(targetId ? `Listing ${targetId} not found in recommendations` : "No recommendations to apply");
    process.exit(1);
  }

  console.log(`${apply ? "APPLYING" : "DRY RUN"}: ${targets.length} listings\n`);

  let success = 0;
  let failed = 0;
  let skipped = 0;

  for (const rec of targets) {
    const currentSet = new Set(rec.currentTags.map((t) => t.toLowerCase()));
    const recSet = new Set(rec.recommendedTags);
    const hasChanges = rec.recommendedTags.some((t) => !currentSet.has(t)) ||
      rec.currentTags.some((t) => !recSet.has(t.toLowerCase()));

    if (!hasChanges) {
      skipped++;
      continue;
    }

    const ok = await updateTags(rec, token);
    if (ok) success++;
    else failed++;

    // Rate limit: 5 QPS
    if (apply) await new Promise((r) => setTimeout(r, 220));
  }

  console.log(`\nDone: ${success} updated, ${failed} failed, ${skipped} already correct`);
  if (!apply && success > 0) console.log("Run with --apply to push changes");
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
